spring.application.name=Talent-IA
# Configuration de la base de donn?es MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/RH1?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=W7301@jqir#
server.port=8089


# Configuration des propri?t?s Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.client.url=http://localhost:4200/*
# Configuration SMTP pour l'envoi d'e-mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amaniyahyaoui20@gmail.com
spring.mail.password=ntbf blbq ojpw vjrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


cloudinary.cloud-name=dfmn0gj7e
cloudinary.api-key=751567632949743
cloudinary.api-secret=n8VO1vlDXormDr1Lom0V4FTkrRA

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

groq.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=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
groq.model=openai/gpt-oss-20
